### ISSUE TITLE
type error request is null

### ISSUE THREAD

**Issue by onyxau** [husseycoding/ajaxcartpopup#1]
I have found this error using firebug console. The error is : if (request.indexOf("/product/") > 0) {
The other error is:  $$(".cart-table .btn-update")[0].remove(); this one appears when I'm viewing the cart instead of the first one appears on product view.

**Comment by husseycoding** [comment]
It sounds like your theme has some elements removed from the page that are there in the default theme (i.e. cart page update button).  Do you still see these errors using the extension on a clean install with the default theme?

**Comment by onyxau** [comment]
I'll try and let you know.
Thanks for your help.
 


     On Friday, July 3, 2015 9:53 PM, Jonathan Hussey <notifications@github.com> wrote:
   

 It sounds like your theme has some elements removed from the page that are there in the default theme (i.e. cart page update button). Do you still see these errors using the extension on a clean install with the default theme?—

**Comment by husseycoding** [comment]
Going to assume there is no issue here - let me know if this is not the case however.
