### ISSUE TITLE
Display of products with catalog price rule

### ISSUE THREAD

**Issue by husseycoding** [husseycoding/ajaxcartpopup#10]
Reported by one customer:

>We have lots of configurable products - that is, you can select a package size in a select box, then Simple Configurable Products (SCP) extension updates the detail view page, e.g. price, description etc.
>
>This worked fine with ACP _until we introduced catalog price rules (like e.g. 20 percent discount on all carpets).
>
>ACP will NOT take the discount price of a configurable product (variant), Magento's own popup cart will! That's of course a no-go :-(

Sounds like prices are not displaying correctly with catalog price rules applied - need to test and fix as required.

**Comment by husseycoding** [comment]
More detail from the customer:

>I have tracked it down to the addToCart() function in (magento_dir)/skin/frontend/(package)/(theme)/js/ajaxcartpopup.js (line 97). This function is called when someone clicks on the 'Add to cart' button. It starts an AJAX request that is probably answered by some ACP php script and the result json contains all the data about the added product, like price etc. Presumably, this php script retrieves the wrong (= normal) unit price from the Magento DB when it is a configurable product (variant) that is currently under a catalog price rule (like 20 percent off or so)...

**Comment by Nico10** [comment]
I tried to replicate this issue locally on a clean install and both simple products and configurable products with catalog price rules are working fine in the cart. He mentions using SImple COnfigurable Products extension, the issue might be caused by the combination of those two extensions.

@ Jon 
Is this issue a paid support ? Do you want me to try and install SCP and find the issue ?

**Comment by husseycoding** [comment]
If you could run a few tests to see if prices display correctly with catalog price rules applied that would be good - we'll go from there.  It sounds like basically prices in the mini cart popup potentially aren't showing the discounted prices when catalog price rule promotions are applied.

**Comment by husseycoding** [comment]
Hang on, by the above do you mean the main cart or the extension mini cart the prices are showing correctly?

**Comment by Nico10** [comment]
They are both showing correctly on my end in a clean install. That's why I'm asking if I should test with SCP installed also :).

**Comment by husseycoding** [comment]
Ah gotcha, ok well if it's a quick test then yes try installing SCP and see if that breaks the prices - if it does then I'll contact the customer directly to see how they want to proceed as it's likely to be paid support in that instance.

**Comment by Nico10** [comment]
http://www.magentocommerce.com/magento-connect/simple-configurable-products.html

hasn't been updated since 2012 so magento 1.5 tested. Not so strait forward to test so probably a paid support issue. Let me know if you need anything from my end, Maybe ask him what version of magento he is using ?

**Comment by husseycoding** [comment]
Yep, don't bother testing as it's well out of date that extension - I'll contact the customer.
