### ISSUE TITLE
Spinning Wheel stuck

### ISSUE THREAD

**Issue by anumtasia** [husseycoding/ajaxcartpopup#13]
Hello,
I am having this problem at my live site where the spinning wheel gets stuck at the first addition of a product to cart. After refreshing the stuck page it shows that the product has been added at the cart and after that the ajax seems to work perfectly. I have made some html custom changes for the look and feel otherwise the functionality is intact.

What i have tracked down:
1. Checking the ajax call gives the error of "Allowed memory 256 MB exhausted at zend/pdo.php" whereas i have 1024 MB memory limit. This line has the fetchAll() query.
2. Checked the cross domain call. And this is not the case.
3. I have removed query of retrieving images if zend db have some lagging behind but to no avail.

This is a perfect plugin for my needs and i dont want to replace. Can you please help me with this?

**Comment by husseycoding** [comment]
If you are seeing a memory limit error of 256MB reported then that is what your memory limit is.  You should increase and then test again.

**Comment by anumtasia** [comment]
ok, thank you for the reply. Ill look into this and notify you if it fixed the problem.

**Comment by anumtasia** [comment]
Thank you so much, as it seems my memory wasn't updated. Updating that fixed the issue. 

I really like this nifty extension of yours. Happy Coding!

**Comment by tieroom** [comment]
I am seeing the exact same behaviour. My memory is already at 1024 MB and I'm not seeing any error messages. Feel free to see for yourself at http://stage.tieroom.co.uk/neckties

**Comment by husseycoding** [comment]
I've just tested that page and it seems to be working on for me.  If you are still having issues can you open a new issue as it's likely not the same issue as this.
