### ISSUE TITLE
404 error in configuration

### ISSUE THREAD

**Issue by smile34** [husseycoding/ajaxcartpopup#14]
I've installed v1.2.4. The installation went ok, no errors reported.
I can see the "Ajax Cart Popup" menu item in the configuration, but if I click it, I get the "404 Error (Page not found)". 

Reindexed and cache refreshed.
Using Magento 1.7.0.2
php 5.4.44

**Comment by husseycoding** [comment]
Did you log out and back into admin?  This is common when installing a new extension until you do.

**Comment by smile34** [comment]
Working.
Sorry, stupid mistake.
Thanks!
