### ISSUE TITLE
public_html/app/Mage.php on line 547

### ISSUE THREAD

**Issue by geysonx** [husseycoding/ajaxcartpopup#16]
Error after install 1.9.2.2

Fatal error: Class 'HusseyCoding_AjaxCartPopup_Helper_Data' not found in /home/belux/public_html/app/Mage.php on line 547

**Comment by husseycoding** [comment]
Going to need more information than that, the file does exist in the extension, [see here](https://github.com/husseycoding/ajaxcartpopup/blob/master/app/code/community/HusseyCoding/AjaxCartPopup/Helper/Data.php).

Have you done the basics such as disabling compilation before installing, clearing your cache afterwards, logging out and then back into admin.  Not finding a file possibly suggests a compilation error.

**Comment by husseycoding** [comment]
Not enough information, closing issue.
