### ISSUE TITLE
delete item from cart not working after SUPEE7405

### ISSUE THREAD

**Issue by linspb** [husseycoding/ajaxcartpopup#18]
http://stackoverflow.com/questions/34964688/supee-7405-and-cannot-remove-the-cart-item/34972091

**Comment by linspb** [comment]
https://github.com/husseycoding/ajaxcartpopup/pull/19

**Comment by linspb** [comment]
https://github.com/husseycoding/ajaxcartpopup/pull/19

**Comment by husseycoding** [comment]
Already resolved in issue #17
