### ISSUE TITLE
success message showing instead of popup

### ISSUE THREAD

**Issue by RIGRO** [husseycoding/ajaxcartpopup#22]
{"result":"success","message":"Blue Poly Tarps 5' x 7' was added to your shopping cart.","linktext":"\n <\/span>\n Cart<\/span>\n 9<\/span>\n","popuphtml":"

The above message is showing instead of the popup on the product listing page. 
I have altered list.phtml to include a qty form and now cannot get the popup to show only on the inner product page

The relevant part of list.phtml is pasted below. It seems the popup will only show if the onclick function is "setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" but that does not allow me to select qty

Can anyone tell me how to be able to have a qty selector and have the popup work?

relevant part of list.phtml:
 <div class="product-secondary">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>

```
                            <form class="qty_form" action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
```

 <?php if(!$_product->isGrouped()): ?>
 <label for="qty"><?php echo $this->__('Qty') ?>:</label>
 <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
 <?php endif; ?>
                                    <p class="action"><button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick=onclick="this.form.submit()"> <span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
 </form>

```
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
```

**Comment by husseycoding** [comment]
Do you have a link to the site the extension is running on so I can take a look?

**Comment by RIGRO** [comment]
the site is still in development. What exactly did you want to see?

**Comment by husseycoding** [comment]
I want to be able to inspect the ajax requests to the server and see the response.

**Comment by RIGRO** [comment]
You can check it out at www.rigrodesign.com/wip/
http://www.rigrodesign.com/wip/thetarpswholesalerthetarpswholesaler

Thank you

I want to be able to inspect the ajax requests to the server and see the
response.

**Comment by husseycoding** [comment]
Your category page add to cart buttons do not have the correct onclick event.  They should have something along the lines of:

```
setLocation('http://www.rigrodesign.com/checkout/cart/add/uenc/aHR0cDovL2V4dGVuc2lvbnMubG9jYWwvZGVmYXVsdC9lbGVjdHJvbmljcy9jZWxsLXBob25lcy5odG1sP2Rpc2FibGVk/product/17/form_key/cjhZejDVblnZQKoY/')
```

They instead have:

```
this.form.submit()
```

You need to restore the correct onclick event for your theme and ajax add to cart will then work.

**Comment by RIGRO** [comment]
Thank you. I will try it and let you know.

**Comment by RIGRO** [comment]
I have tried to change the onclick event. now I am getting the loading icon
but the success message does not show and the item is not added to the cart

What should I change the onclick event to instead?

**Comment by husseycoding** [comment]
The string I put above is not what you should use, it was an example of the format of the string which should appear when the buttons are being generated correctly.  You need to compare your template to the core one and restore the normal way of generating the add to cart buttons.  If this is not something you are sure how to do then you will need to get paid support.
