### ISSUE TITLE
One pcs on stock

### ISSUE THREAD

**Issue by sgureev** [husseycoding/ajaxcartpopup#23]
When the stock goods in a single copy of the product and presence management is enable. I have message in popupcart  with the error that store don't have anought of items. After refresh page the error dont appearing.

**Comment by husseycoding** [comment]
Ajax Cart Popup doesn't do anything in determing whether a product is in stock or not, messages are only displayed if they are generated by the store.  You should check if you have any other extension/logic running which may have an affect on this.
