### ISSUE TITLE
different styles

### ISSUE THREAD

**Issue by olfedos** [husseycoding/ajaxcartpopup#24]
Can I define other id and class for window when addition to the cart?
I want to have different styles for the window when click addtocart button and when click the mini cart icon.
Thanks!

**Comment by husseycoding** [comment]
There isn't any built in functionality to do that, but the extension is totally open source so you can change anything you like.  Feel free to fork the repository and make your own version of the extension or just install and edit as needed.

**Comment by olfedos** [comment]
Thanks for answer!)
What kind changes must be made in the code to realize this?

**Comment by husseycoding** [comment]
The styles are all in the [css file](https://github.com/husseycoding/ajaxcartpopup/blob/master/skin/frontend/base/default/css/ajaxcartpopup.css) and the HTML generated for the notice shown after adding to the cart is in [this template file](https://github.com/husseycoding/ajaxcartpopup/blob/master/app/design/frontend/base/default/template/ajaxcartpopup/notice.phtml).
