### ISSUE TITLE
only loading

### ISSUE THREAD

**Issue by pratik9695** [husseycoding/ajaxcartpopup#27]
this extensiion in localhost complate work but my hostig site in only loading not pop up cart page.plz help me

**Comment by husseycoding** [comment]
It's not meant to load on the cart or checkout pages as the cart contents are displayed there anyway.  Is that what you mean?

**Comment by pratik9695** [comment]
means when extension use in localhost. is work perfect but when extension use in live website (host) in only loading and loading not cart open but continue loading.

**Comment by husseycoding** [comment]
Ok, well you should determine the differences between your local development environment and your live environment.  Also consider things like caching and compilation which might be active live, but not locally.  As it's working locally for you I'll close the issue, but if you suspect there is a problem with the extension then just let me know, equally if you want paid support we can do that too.
