### ISSUE TITLE
Enable or disable for Store?

### ISSUE THREAD

**Issue by rskonieczka** [husseycoding/ajaxcartpopup#36]

**Comment by rskonieczka** [comment]
How do I enable ajax cart for the selected template? Thank you for your help

**Comment by husseycoding** [comment]
You can disable the extension for a particular store by changing the store configuration scope and setting the enabled/disabled status here instead of at global scope.  Does that make sense?

**Comment by rskonieczka** [comment]
@husseycoding Thank you for your help
