### ISSUE TITLE
Os produtos só estão sendo adicionados ao carrinho após atualizar a página manualmente. E ocorre este erro: Uncaught TypeError: Cannot read property 'viewport Offset' of undefined

### ISSUE THREAD

**Issue by ThaiMedeiros** [husseycoding/ajaxcartpopup#39]
Eu inseri o plugin, mas ele não está funcionando, não aparece a "janelinha" ao clicar no botão para adicionar ao carrinho, e quando clica só aparece como se vai carregar, e só mostra que o produto foi adicionado ou excluído após atualização manual da página. E está ocorrendo este erro: Uncaught TypeError: Cannot read property 'viewport Offset' of undefined. Se alguém puder ajudar, desde já agradeço.

**Comment by husseycoding** [comment]
Sorry, you are going to have to put that in English.

**Comment by ThaiMedeiros** [comment]
The products are only being added to the cart after refresh the page manually. And this error occurs: Uncaught TypeError: Can not read property 'viewport Offset' of undefined (# 39)

I inserted the plug, but it's not working, does not appear to "small window" by clicking the button to add to cart, and when you click only appears as if it will carry, and only shows that the product has been added or deleted after updating page. And this is occurring error: Uncaught TypeError: Can not read property 'viewport Offset' of undefined. If anyone can help, I thank you.

**Comment by husseycoding** [comment]
Whats the URL of the store you are using the extension on?

**Comment by ThaiMedeiros** [comment]
I cannot pass

**Comment by husseycoding** [comment]
Ok, well without the site to look at there is very little I can do as I have no idea how the site has been developed.  I'll close the issue, but if you are able to give more information just add it here.
