### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by Terry0421** [husseycoding/ajaxcartpopup#4]
Hi, I am Terry.

I am using Magento 1.7.0.2 and not default theme.

I downloaded this extension and activated followed the instruction ( set "Yes" on Enabled area on config page), but nothing was coming up on header so far.

Do I have to do something like calling php function on header.phtml?

I am beginner to Magento, please help me!!

Thanks

**Comment by husseycoding** [comment]
If the right elements are in place you don't need to do anything.  Whats the address of your site?

**Comment by Terry0421** [comment]
This is the address of my site
http://mishkataiwan.com/index.php/

**Comment by husseycoding** [comment]
The standard element structure and class names have been altered for the header cart link - you will need to restore this if you want the extension to work unmodified.  Otherwise you are of course free to customise the extension to your needs.

**Comment by Terry0421** [comment]
I know this is stupid questions though...Could you please tell me what the standard element structure and class names are need or do you have any idea to restore this easily?

I took this website from someone in the middle, so i am not sure what it looked like before...

Thanks

**Comment by husseycoding** [comment]
Probably you can just add the class top-link-cart to the element which currently has an id of cart.

**Comment by husseycoding** [comment]
Assuming you have sorted this now - closing as it's not something that needs to be worked for the extension.
