### ISSUE TITLE
Ajax popup can't load

### ISSUE THREAD

**Issue by ymarc77** [husseycoding/ajaxcartpopup#41]
When I click "add to cart" the icon is spinning and nothing more. 

And error:

```
TypeError: $$(...)[0] is undefined
ajaxcartpopup.js (line 326, column 24)

```
Is it theme related error? I use this ebajes theme; https://www.halothemes.com/theme/ebajes-free-responsive-electronics-magento-ce-theme demo: http://demo.halothemes.com/ebajes-free-responsive-electronics-magento-ce-theme

**Comment by husseycoding** [comment]
Almost definitely yes, see that line [here](https://github.com/husseycoding/ajaxcartpopup/blob/master/skin/frontend/base/default/js/ajaxcartpopup.js#L326).
