### ISSUE TITLE
Minor Issues in   Ajax Cart Popup magento extension 

### ISSUE THREAD

**Issue by vittal55** [husseycoding/ajaxcartpopup#43]
First of thanks for the great extension. Its really appreciable.
However there is minor issue with this extenion.
Some time while adding products to cart instead of POP UP a blank page appears with code written as    

> {"result":"success","message":"Product Description was added to your shopping cart.","linktext":"\n <\/span>\n Cart<\/span>\n 3<\/span>\n","popuphtml":" ).

Please help me out how to resolve this issue to use this wonderful extension trouble free.

**Comment by husseycoding** [comment]
Hmm right ok.  Any chance you have found steps to reliably reproduce the issue?  It sounds to me like the add to cart request in these cases is not being sent as an AJAX request and you are seeing the JSON response.

**Comment by vittal55** [comment]
Hi,
I am using this  extension (Ajax Cart Popup)  on my website  " besidemart.tk" . I have added products in only one sub category i.e  Sub category: Health Care  under the  Main Category :Patanjali Products

In the product list   of Health care  , no issues while adding products to cart from 1st Page. However when we move to second page and add products to cart, the issue which i mentioned above occurs i.e blank page with html text says 
 

> {"result":"success","message":"Patanjali Tulsi Panchang Juice 500 ml was added to your shopping cart.","linktext":"\n <\/span>\n Cart<\/span>\n 3<\/span>\n","popuphtml":"

Thank you

**Comment by husseycoding** [comment]
When you say move to a second page, what do you mean exactly?  A quick test shows add to cart to be working correctly for category and product pages for me.

**Comment by vittal55** [comment]
Hi, 
    Sorry for the confusion. Moving to the next page means, I have 36 products in the Health Care subcategory. But only 12 products are displayed at once, to see the next 12 products we have to move to the second page. That's what I mean"moving to the second page".

**Comment by husseycoding** [comment]
Ok, yep that's because the page is updated via AJAX, but the add to cart observers are only added on page load.  You'll need to do something like call the JS method thiscartpopup.afterInit(); when the new page of products has loaded to add the required observers.

**Comment by vittal55** [comment]
Hi,
   Thanks for ur quick response. I am not a programmer (good at programming). So, please can you help me in step by step solution.

Thank you

**Comment by husseycoding** [comment]
I think you wouild be best off asking your store developer to look at it but I have tested the solutuion I suggest above and it does work.  If you want us to look at we can but it would be paid support.

**Comment by vittal55** [comment]
I would be  to take support from you.
But with the existing issue i need one more feature in my store.

I need a "delivery schedule" module for my Magento 1.9.2.4

The required features in Delivery Schedule are 
1) The customer may have flexibility of choosing delivery of products from present day to next 4 days ( showing date and Weekdays) with 3 or 2 delivery slots per day.
2) Admin should have the flexibility of defining the  time slots  , and window period before which the slot can be chosen.
3) The chosen time slot should reflect with day should reflect in emails of customer order email., and admin copy.

Please let me know your charges of paid support of issue in add to cat pop up and delivery schedule

**Comment by husseycoding** [comment]
Ok, I'll cliose this issue as it's a theme specific issue and you would like paid support.  Can you drop the above information in an email to support@husseycoding.co.uk and we can discuss there.
