### ISSUE TITLE
404! with magento 1.9.2.4

### ISSUE THREAD

**Issue by amanullah-1** [husseycoding/ajaxcartpopup#44]
Hi 

I was trying to use it with my magento 1.9.2.4.
after installing when I goes to System -> Configuration -> Hussey Coding -> Ajax Cart Popup  
it shows a 404 error. 
Can you pls check and resolve the issue?

Thanks and regards
Md Aman Ullah

**Comment by tieroom** [comment]
That's standard behaviour after installing any extension. Have you tried clearing the cache and then logging out of the admin and back in again?

**Comment by husseycoding** [comment]
As above, this is not a bug.  Log out and back into admin and retry.
