### ISSUE TITLE
Cannot remove from the original cart page

### ISSUE THREAD

**Issue by mydialand** [husseycoding/ajaxcartpopup#48]
Hello, thank you for the amazing module!

But one issue was found. I cannot remove items from the original cart page. When I try to remove items hitting the remove item button on the original cart page, it shows me the circling loading icon but it never does anything but stays in the same page, does not remove the item.

Other than this, everything else works fine so far. I can edit the quantity to zero, and clear the shopping cart. I can remove items from the drop down cart.

Please let me know! Thank you very much.

**Comment by husseycoding** [comment]
What's your store URL?

**Comment by mydialand** [comment]
http://mydialand.com/

Thank you for your quick reply

**Comment by husseycoding** [comment]
You have a similar issue adding products to the cart on category pages.  Oddly even though the spinner shows the add to/remove from cart request isn't even being sent.  Have you altered the extension at all?

**Comment by mydialand** [comment]
One thing I changed was not to show 'quantity' error message for the drop down popup cart, because it was showing the 'quantity not available' message when the quantity is there. I just commented out the line so it wont change the function of the extension.

**Comment by mydialand** [comment]
But on my end, the adding function works fine. I can add items, takes a little bit of time to process, but it works.

**Comment by mydialand** [comment]
I got the solution. I just removed the following class: 

class="btn-remove btn-remove2"

and replaced the button to text. Now it works. I do not know why the text makes difference.

Thank you for the amazing module anyway!

**Comment by husseycoding** [comment]
Glad you got it sorted.
