### ISSUE TITLE
Popup not showing + Cart update

### ISSUE THREAD

**Issue by scherfro** [husseycoding/ajaxcartpopup#5]
Hello,

I recently installed your module but the popup is not showing after adding the products to cart, everything is enabled.

What could be the problem?

Thanks.

**Comment by husseycoding** [comment]
Can you test the same thing on a clean, unmodified Magento install (not developed or skinned) and if you still have an issue come back with some more details.  If you see an issue on your install but not a clean install we can resolve it, but it will be paid support.

**Comment by husseycoding** [comment]
Nor enough information, closing issue.
