### ISSUE TITLE
404 get request when add to cart

### ISSUE THREAD

**Issue by cdpi404** [husseycoding/ajaxcartpopup#51]
Hello 
First of all, thanks to the community for the help provided. I do not understand on my site when I click on add to cart i have one error in google console. Not fount 404. And the spinner at the center.
The site of my client is http://www.germedevie.fr you can try on all the buttons to add to the ponier. Thank you

**Comment by husseycoding** [comment]
The AJAX cart functionality on the site isn't provided by this extension.

**Comment by cdpi404** [comment]
Sorry we left the two plugin activated, now we have activated the good one and we face the same problem, we still can't add any item to the cart...

Thank in advance

**Comment by husseycoding** [comment]
Well one thing which is immediately obvious is that there is a 301 redirect from the add to cart url which *may* be having an affect.  Your site it extremely heavily customised - it's not realistic to be able to debug this for you for free but the add to cart URL should at least give you a starting point.
