### ISSUE TITLE
ajaxcartpopup 

### ISSUE THREAD

**Issue by pradeep41988** [husseycoding/ajaxcartpopup#7]
I am using this extenstion but not working properly. 
Below url
http://www.happyshoppi.com/index.php/women/indian-wear/salwar-suits.html

**Comment by husseycoding** [comment]
We can look at the issues you are seeing, but as you are using the extension on a customised install it would need to be paid support (unless you can prove an issue on a clean install).  For paid support drop us an email at support@husseycoding.co.uk.

My suggestion would be to get your store developer to look at it, I'm sure they will be able to get things working for you.
