### ISSUE TITLE
sidebar not updating

### ISSUE THREAD

**Issue by stela22** [husseycoding/ajaxcartpopup#8]
Hi!
I have a problem with Ajax Cart Popup Extention. When i add a new product in my basket i have to refresh the page to see that product in my sidebar cart.

https://i.gyazo.com/9a79e84781f1a0315ee800639cf60f73.gif

**Comment by husseycoding** [comment]
As you are using the extension on a customised install we can offer you support but it will be paid unless you can show there is an issue on a clean unmodified Magento install.  You can request paid support through the support tab on our store.

http://store.husseycoding.co.uk/

If you do prove an issue with the extension on a clean install then we will of course fix this for the next release free of charge - just re-open the issue in this case.
